In [1]:
import numpy as np

In [2]:
x=np.array([[1,0,2],[3,4,6],[3,7,9]])

In [3]:
y=np.array([[1,0,5],[3,3,6],[1,7,2]])

In [4]:
x+y

array([[ 2,  0,  7],
       [ 6,  7, 12],
       [ 4, 14, 11]])

In [5]:
x*y

array([[ 1,  0, 10],
       [ 9, 12, 36],
       [ 3, 49, 18]])

In [6]:
z=np.array([1,4,7,9,0,3])

In [7]:
z.dtype

dtype('int32')

In [8]:
np.sqrt(z)

array([1.        , 2.        , 2.64575131, 3.        , 0.        ,
       1.73205081])

In [9]:
np.sum(z)

24

In [10]:
np.max(z)

9

In [11]:
x

array([[1, 0, 2],
       [3, 4, 6],
       [3, 7, 9]])

In [12]:
np.where(x>5)

(array([1, 2, 2], dtype=int64), array([2, 1, 2], dtype=int64))

In [13]:
np.count_nonzero(x)

8

In [14]:
np.nonzero(x)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [15]:
py_ar=[1,55,4,3]

In [16]:
import sys

In [17]:
sys.getsizeof(1) * len(py_ar)

112

In [18]:
py_ar=np.array(py_ar)

In [19]:
py_ar.itemsize * py_ar.size

16

In [20]:
py_ar

array([ 1, 55,  4,  3])

In [21]:
py_ar.tolist()

[1, 55, 4, 3]