In [1]:
import numpy as np 

In [2]:
myarray = np.array([[1,2,4],[4,7,5],[2,8,9]])

In [3]:
myarray

array([[1, 2, 4],
       [4, 7, 5],
       [2, 8, 9]])

In [4]:
myarray.sum(axis=0)

array([ 7, 17, 18])

In [5]:
myarray.sum(axis=1)

array([ 7, 16, 19])

In [6]:
myarray.T

array([[1, 4, 2],
       [2, 7, 8],
       [4, 5, 9]])

In [7]:
myarray.flat


In [8]:
for i in myarray.flat:
    
    print(i)

1
2
4
4
7
5
2
8
9


In [9]:
myarray.ndim

2

In [10]:
myarray.nbytes

36

In [11]:
x=[12,4,57,8,2,1]

In [12]:
x=np.array(x)

In [13]:
x

array([12,  4, 57,  8,  2,  1])

In [14]:
x.argmax()

2

In [15]:
x.argmin()

5

In [16]:
x.argsort()

array([5, 4, 1, 3, 0, 2], dtype=int64)

In [17]:
y=[[1,3,0],[5,7,9],[2,4,7]]

In [18]:
y=np.array(y)

In [19]:
y

array([[1, 3, 0],
       [5, 7, 9],
       [2, 4, 7]])

In [20]:
y.flat

In [21]:
y.argmax()

5

In [22]:
y.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [23]:
y.argmin(axis=1)

array([2, 0, 0], dtype=int64)