In [5]:
import numpy as np

In [ ]:
arr1=np.array([1,3,5,7],dtype=np.int64)


In [ ]:
arr1.size

In [ ]:
arr1.shape

In [ ]:
arr1.dtype

In [ ]:
arr1[0]

In [ ]:
arr1[0] = 34

In [ ]:
arr1

In [ ]:
arr1.itemsize

In [ ]:
emp=np.empty(10)

In [ ]:
emp

In [ ]:
lspace=np.linspace(1,5,7)

In [ ]:
lspace

In [6]:
arr2=np.array([[1,3,5],[6,8,9]])

In [7]:
arr2.itemsize

4

In [10]:
arr2.sum(axis=1)

array([ 9, 23])

In [11]:
arr2

array([[1, 3, 5],
       [6, 8, 9]])

In [12]:
arr2.T

array([[1, 6],
       [3, 8],
       [5, 9]])

In [15]:
arr3=np.identity([12,4])

TypeError: 'list' object cannot be interpreted as an integer